### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by prkos0** [EmmanuelBeziat/jquery-awesomodals#1]
Awesome plugin btw, for google chrome that is ;)

FF console log:

> ReferenceError: event is not defined
> .modalOpen()
> .bindEvents/<()
> r.event.dispatch()
> r.event.add/q.handle()

Cheers

EDIT: Last 2 lines are jquery errors

**Comment by EmmanuelBeziat** [comment]
Thanks for this, I’ll check asap.
Firefox events error happens a bit too often.

I plan to rebuild this plugin as a vanilla JS plugin, not requiring jQuery, though. But I’ll fix this point first.

Thanks again !

**Comment by EmmanuelBeziat** [comment]
This is fixed now. Thanks for sharing the issue!
